### ISSUE TITLE
Error on making first wiki

### ISSUE THREAD

**Issue by kookma** [inmysocks/PluginDevelopment#2]
It seems one needs to make `Wikis` directory in advance
Run the MakeWiki.sh shows an error like below

```
Error: Error creating directory './Wikis/nella'
New wiki created in /c/Temp/PluginDevelopment-master/Wikis/ using empty edition
```

While it says a new wiki is created but it is not correct!

If I make the Wikis manually then it works fine

**Comment by inmysocks** [comment]
I am going to blame this one on windows and it inability to handle file paths correctly. I have changed it to use the absolute path to the folder which may fix the problem, if not try doing this and see if it given an error, if so it may be a problem with the tiddlywiki core.

in the PluginDevelopment folder type

`node ./TiddlyWiki5/tiddlywiki.js ./test/wiki --init empty`

it should create an empty wiki in the folder test/wiki, if not we should fix that in the core.

**Comment by kookma** [comment]
Okay, I clone the repo again and will back to you

**Comment by kookma** [comment]
May I ask to create Wikis folder like Plugins Themes , ... folder!
I still get error on nested folder! I mean first plugin needs to create like Wikis/author/

**Comment by inmysocks** [comment]
Windows and its weird pathing is going to be the death of me.
The script is updated to create the folder.

But I still would like to know if this command creates a wiki or not:

`node ./TiddlyWiki5/tiddlywiki.js ./test/wiki --init empty`

**Comment by kookma** [comment]
Jed,

I checked both using Powershell, bash (from Msys2), cmd.exe and get the below error

```
Mohammad@N550JK  /c/TW/JDLIB/PluginDevelopment
$ node ./TiddlyWiki5/tiddlywiki.js ./test/wiki --init empty
Error: Error creating directory './test/wiki'
```

Seems nested directory cannot be created by node.js

**Comment by inmysocks** [comment]
Then the problem is with node and windows, I don't know if there is a fix or not.

Creating wikis like that works on both OS X and linux.
Pathing on windows is strange so people run into a lot of problems on windows that I have no way of finding.

**Comment by kookma** [comment]
Jed,

In `MakePlugin.sh` you have used the below code

```
if [ -d "$PLUGINFOLDER/$AUTHOR" ]; then
  mkdir "$PLUGINFOLDER/$AUTHOR/$PLUGINNAME"
else
  mkdir "$PLUGINFOLDER/$AUTHOR"
  mkdir "$PLUGINFOLDER/$AUTHOR/$PLUGINNAME"
fi
```

What do you think if a similar script is used for making test wiki!

A comment can be added to explain it is because of Windows issue.

**Comment by inmysocks** [comment]
If you want to make pull request feel free, otherwise I think that the problem should be handled in the tiddlywiki core.

**Comment by kookma** [comment]
Good,
 I make a PR here and will submit issue on Tiddlywiki.com!

The documentation is now very useful! Thank you for all your efforts.

**Comment by kookma** [comment]
Hi @inmysocks 
It was found the error on nested directory is because of bash 4.4.23 (from msys2)  on Windows 10!
So, I think there is no need to make any change to the repo!

Thank you again Jed
I will announce the repo on Google Forum!
